# Generated by Django 6.0.1 on 2026-01-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userprofile_avatar_userprofile_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="village",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(
                default="profiles/default.png", upload_to="profiles/"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("instructor", "Instructor"),
                    ("admin", "Admin"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
