# Generated by Django 6.0.1 on 2026-01-26 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_userprofile_department_userprofile_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="department",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="profile_image",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="year",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="enrolled_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(default="student", max_length=20),
        ),
    ]
