# Generated by Django 6.0.1 on 2026-01-30 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_assignment_grade"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="grade",
            name="course",
        ),
        migrations.RemoveField(
            model_name="grade",
            name="created_at",
        ),
        migrations.AddField(
            model_name="grade",
            name="marks",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="grade",
            name="subject",
            field=models.CharField(default="Unknown", max_length=100),
        ),
        migrations.AlterField(
            model_name="grade",
            name="grade",
            field=models.CharField(default="NA", max_length=2),
        ),
        migrations.AlterField(
            model_name="grade",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Assignment",
        ),
    ]
